version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/disjudge
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 300
     runas: root
   - location: scripts/createEnv
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start
     timeout: 300
     runas: root
