version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/disjudge
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
   - location: scripts/stop
     timeout: 60
     runas: root
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 500
     runas: root
  ApplicationStart:
   - location: scripts/start
     timeout: 60
     runas: root
