#!/bin/bash
cp /home/ec2-user/disjudge-secrets/.env /home/ec2-user/disjudge
sudo pip3 install virtualenv
cd /home/ec2-user/disjudge
virtualenv environment
cd /home/ec2-user/disjudge
source environment/bin/activate
# might need sudo here?
pip3 install -r ./src/requirements.txt
