#!/bin/bash
sudo pip3 install virtualenv
cd /home/ec2-user/disjudge
virtualenv environment
cd /home/ec2-user/
git clone git@github.com:patrickzebinghe/disjudge-secrets.git
cp ./disjudge-secrets/.env ./disjudge
cd /home/ec2-user/disjudge
source environment/bin/activate
pip3 install -r ./src/requirements.txt
