#!/bin/bash
cp ~/disjudge-secrets/.env ~/disjudge
sudo pip3 install virtualenv
cd ~/disjudge
virtualenv environment
cd ~/disjudge
source environment/bin/activate
pip3 install -r ./src/requirements.txt
